"""Migración inicial: 16 tablas con enmiendas A1-A4

Revision ID: e099aa7f38d8
Revises: 
Create Date: 2026-09-12 02:54:24.509629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e099aa7f38d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tabla', sa.Text(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.Enum('creacion', 'edicion', 'eliminacion', 'login_fallido', name='accionauditoria'), nullable=False),
    sa.Column('datos_antes', sa.Text(), nullable=True),
    sa.Column('datos_despues', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('regimen', sa.Enum('unipersonal_prof', 'unipersonal_no_prof', 'monotributo', 'pequena_empresa', 'regimen_general', 'persona_fisica', name='regimen'), nullable=False),
    sa.Column('rut', sa.Text(), nullable=True),
    sa.Column('ci', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos_ingresos_propios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('ingreso', 'gasto', name='tipomovimientopropio'), nullable=False),
    sa.Column('concepto', sa.Text(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria', sa.Enum('cjppu', 'aportes_bps', 'gasto_operativo', 'otro', name='categoriamovimientopropio'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduler_ejecuciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proceso', sa.Enum('diario', 'mensual', name='procesoscheduler'), nullable=False),
    sa.Column('fecha_ejecucion', sa.DateTime(), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('frecuencia', sa.Enum('mensual', 'anual', 'unico', name='frecuenciaservicio'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_login',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vencimientos_calendario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('regimen', sa.Enum('unipersonal_prof', 'unipersonal_no_prof', 'monotributo', 'pequena_empresa', 'regimen_general', 'persona_fisica', 'todos', name='regimenaplicable'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('organismo', sa.Enum('dgi', 'bps', 'otro', name='organismo'), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('dia_vencimiento', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes_regimen_historial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('regimen', sa.Enum('unipersonal_prof', 'unipersonal_no_prof', 'monotributo', 'pequena_empresa', 'regimen_general', 'persona_fisica', name='regimen'), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credenciales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('dgi', 'bps', 'facturador', 'clave_dgi', 'otro', name='tipocredencial'), nullable=False),
    sa.Column('usuario', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('ultima_actualizacion', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios_contratados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarea_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('regimen', sa.Enum('unipersonal_prof', 'unipersonal_no_prof', 'monotributo', 'pequena_empresa', 'regimen_general', 'persona_fisica', 'todos', name='regimenaplicable'), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('mes_generacion', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cobros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('servicio_contratado_id', sa.Integer(), nullable=True),
    sa.Column('periodo_desde', sa.Date(), nullable=True),
    sa.Column('periodo_hasta', sa.Date(), nullable=True),
    sa.Column('fecha_cobro', sa.Date(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pago', sa.Enum('efectivo', 'transferencia', 'otro', name='formapago'), nullable=False),
    sa.Column('tipo_comprobante', sa.Enum('e_ticket', 'no_gravado', 'sin_comprobante', name='tipocomprobante'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_contratado_id'], ['servicios_contratados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('descuentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('servicio_contratado_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_contratado_id'], ['servicios_contratados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('honorarios_historial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('servicio_contratado_id', sa.Integer(), nullable=False),
    sa.Column('honorario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_contratado_id'], ['servicios_contratados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('servicio_contratado_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'en_proceso', 'completada', 'cancelada', name='estadotarea'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_completada', sa.DateTime(), nullable=True),
    sa.Column('requiere_info_cliente', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_contratado_id'], ['servicios_contratados.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['tarea_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recordatorios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('tarea_pendiente', 'vencimiento_proximo', 'cobro_pendiente', name='tiporecordatorio'), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha_programada', sa.DateTime(), nullable=False),
    sa.Column('fecha_enviada', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'enviado', 'silenciado', 'cerrado', name='estadorecordatorio'), nullable=False),
    sa.Column('repetir_hasta_completar', sa.Boolean(), nullable=False),
    sa.Column('intervalo_repeticion_horas', sa.Integer(), nullable=True),
    sa.Column('silenciado_hasta', sa.Date(), nullable=True),
    sa.Column('vencimiento_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('periodo', sa.Date(), nullable=True),
    sa.Column('umbral_dias', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ),
    sa.ForeignKeyConstraint(['vencimiento_id'], ['vencimientos_calendario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recordatorios')
    op.drop_table('tareas')
    op.drop_table('honorarios_historial')
    op.drop_table('descuentos')
    op.drop_table('cobros')
    op.drop_table('tarea_templates')
    op.drop_table('servicios_contratados')
    op.drop_table('credenciales')
    op.drop_table('clientes_regimen_historial')
    op.drop_table('vencimientos_calendario')
    op.drop_table('usuario_login')
    op.drop_table('servicios')
    op.drop_table('scheduler_ejecuciones')
    op.drop_table('gastos_ingresos_propios')
    op.drop_table('clientes')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
